server:
  port: 9090
  
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9090/oauth/token
    client:
      client-id: my-client
      client-secret: secretpassword
      user-authorization-uri: http://localhost:9090/user
      authentication-scheme: form
      scope:
      - webclient
      grant-type: password  

          
      